#### Reinforcement Learning and Decision Making &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Homework #1

# &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Planning in MDPs

## Description

You are given an $N$-sided die, along with a corresponding Boolean mask
vector, `is_bad_side` (i.e., a vector of ones and zeros). You can assume
that $1<N\leq30$, and the vector `is_bad_side` is also of size $N$ and
$1$ indexed (since there is no $0$ side on the die). The game of DieN is
played as follows:

1.  You start with $0$ dollars.

2.  At any time you have the option to roll the die or to quit the game.

    1.  **ROLL**:

        1.  If you roll a number not in `is_bad_side`, you receive that
            many dollars (e.g., if you roll the number $2$ and $2$ is
            not a bad side -- meaning the second element of the vector
            `is_bad_side` is $0$, then you receive $2$ dollars). Repeat
            step 2.

        2.  If you roll a number in `is_bad_side`, then you lose all the
            money obtained in previous rolls and the game ends.

    2.  **QUIT**:

        1.  You keep all the money gained from previous rolls and the
            game ends.

## Procedure

-   You will implement your solution using the `solve()` method
    in the code below.
    
-   Your return value should be the number of dollars you expect to
    win for a specific value of `is_bad_side`, if you follow an
    optimal policy. That is, what is the value of the optimal
    state-value function for the initial state of the game (starting
    with $0$ dollars)? Your answer must be correct to $3$ decimal
    places, truncated (e.g., 3.14159265 becomes 3.141).

-   To solve this problem, you will need to determine an optimal policy
    for the game of DieN, given a particular configuration of the die.
    As you will see, the action that is optimal will depend on your
    current bankroll (i.e., how much money you've won so far).

-   You can try solving this problem by creating an MDP of the game
    (states, actions, transition function, reward function, and assume a
    discount rate of $\gamma=1$) and then calculating the optimal
    state-value function.

## Resources

The concepts explored in this homework are covered by:

-   Lecture Lesson 1: Smoov & Curly's Bogus Journey

-   Chapter 3 (3.6 Optimal Policies and Optimal Value Functions) and
    Chapter 4 (4.3-4.4 Policy Iteration, Value Iteration) of
    http://incompleteideas.net/book/the-book-2nd.html

-   Chapters 1-2 of 'Algorithms for Sequential Decision Making', M.
    Littman, 1996

## Submission

-   The due date is indicated on the Canvas page for this assignment.
    Make sure you have your timezone in Canvas set to ensure the
    deadline is accurate.

-   Submit your finished notebook on Gradescope. Your grade is based on
    a set of hidden test cases. You will have unlimited submissions -
    only the last score is kept.

-   Use the template below to implement your code. We have also provided
    some test cases for you. If your code passes the given test cases,
    it will run (though possibly not pass all the tests) on Gradescope.

-   Gradescope is using *python 3.6.x* and *numpy==1.18.0*, and you can
    use any core library (i.e., anything in the Python standard library).
    No other library can be used.  Also, make sure the name of your
    notebook matches the name of the provided notebook.  Gradescope times
    out after 10 minutes.

In [24]:
#################
# DO NOT REMOVE
# Versions
# numpy==1.18.0
################
import numpy as np

    

class MDPAgent(object):
    def __init__(self):
        self.money_gain = 0
        pass
    
    def expectation(self, is_bad_side, money_gain):
        """Calculate expectation according to die type and current gain"""
        die_size = len(is_bad_side)
        is_bad_side = np.array(is_bad_side)
        exp = (sum(np.where(is_bad_side== 0)[0]+1) - (np.count_nonzero(is_bad_side==1))*money_gain)/die_size
        
        return exp
    
    def rollresult(self, is_bad_side, money_gain):
        """the result of this roll"""
        # v value
        die_size = len(is_bad_side)
        result = np.zeros(die_size)
        for i in range(0, die_size):
            if is_bad_side[i] == 1:
                # forefeit all money
                result[i] = - money_gain
            elif is_bad_side[i] == 0:
                # add die number
                result[i] = i + 1
        
        return result
    
    def exp_threashold(self, is_bad_side, money_gain):
        """Calculate max_gain that have a positive expectation"""
        max_current = 0
        flag = 1
        while flag == 1:
            max_current = max_current + 1
            # print(self.expectation(is_bad_side, money_gain = max_current))
            if self.expectation(is_bad_side, max_current) < 0:
                flag = 0
            # print(max_current)
            
        return max_current - 1
    
    def decision(self, is_bad_side, money_gain):
        die_size = len(is_bad_side)
        quit_reward = money_gain
        roll_reward = money_gain + self.expectation(is_bad_side, money_gain)
     

    def solve(self, is_bad_side):
        """Implement the agent"""
        money_gain = self.money_gain 
        # for value > max_current, skip calculating expectation
        max_current = self.exp_threashold(is_bad_side, money_gain)
        print('max current = ', max_current)

        
        # step 1. determine maximum roll number
        # if expectations are all negative or zero, stop
        
        # initial roll must be able to run unless all sides are bad or all good
        is_bad_side = np.array(is_bad_side)
        
        if (is_bad_side == 1).sum() == len(is_bad_side):
            # all sides are bad
            exp = 0
        elif (is_bad_side == 0).sum() == len(is_bad_side):
            # all sides are good
            exp = 999999999
        else: 
            # search maximum depth 
            ini_exp = self.expectation(is_bad_side, money_gain)
            ini_result = self.rollresult(is_bad_side, money_gain)
            result = self.rollresult(is_bad_side, money_gain)

            ita = 2
            die_size = len(is_bad_side)
            num_states = ita * die_size + 2
            
            # find good sides
            is_bad_side = np.array(is_bad_side)
            good_sides_store = -is_bad_side + 1
            
            ini_roll = self.rollresult(is_bad_side, money_gain)
            
            p_matrix = np.zeros((2, num_states, num_states))
            np.fill_diagonal(p_matrix[0], 1)
            p = 1.0 / die_size
            zero = np.zeros((ita - 1) * die_size + 2)

            # explore the possibilty of keep rolling
            good_sides_store_n = np.concatenate((np.concatenate((np.array([0]), good_sides_store, zero), axis=0), 
                                             np.concatenate((np.array([0]), good_sides_store, zero), axis=0)), axis=0)
            
            temp = np.concatenate((np.array([0]), good_sides_store, zero), axis=0)
            for i in range(0, ita * die_size + 2):
                good_sides_store_n = np.concatenate((good_sides_store_n, temp), axis=0)
            
            good_sides_store_n = good_sides_store_n[:(num_states ** 2)].reshape(num_states, num_states)

            p_matrix[1] = good_sides_store_n*p
            
            # determine if stop/quit at each iteration
            p_matrix_of_quit = 1 - np.sum(p_matrix[1, :num_states, :num_states-1], axis=1).reshape(-1, 1)

            p_matrix[1] = np.concatenate((p_matrix[1, :num_states, :num_states-1], p_matrix_of_quit), axis=1)
            
            gain_store = np.zeros((2, num_states, num_states))

            ## calculate reward based on previous exploration      
            dollar_n = np.concatenate((np.concatenate((np.array([0]), ini_roll, zero), axis=0),
                                       np.concatenate((np.array([0]), ini_roll, zero), axis=0)), axis=0)
            
            temp_gain = np.concatenate((np.array([0]), ini_roll, zero), axis=0)
            for i in range(0, ita * die_size + 2):
                dollar_n = np.concatenate((dollar_n, temp_gain), axis=0)
            
            dollar_n = dollar_n[:(num_states ** 2)].reshape(num_states, num_states)

            gain_store[1] = dollar_n
            gain_store[1] = np.concatenate((gain_store[1, :num_states, :num_states-1],
                                         -np.array(range(0, num_states)).reshape(-1, 1)), axis=1)
            
            # iteratively find the max (variable 'ita' was used previously)
            
            ita_n = 0
            max_ita = 20
            
            print(p_matrix[0])
            print(np.round(p_matrix[1],2))
            print(p_matrix.shape)
            print(gain_store[0])
            print(np.round(gain_store[1],2))
            print(gain_store.shape)
            
            print('v temp 1 is: ', np.multiply( np.round(p_matrix[1],2), np.round(gain_store[1],2))  )
            # print(gain_store)
            # print(gain_store)

#             gain_iteration = ValueIteration(p_matrix, gain_store, 1)
#             gain_iteration.run()

#             exp_store = gain_iteration.V
#             exp = (max(exp_store))
            exp = 1
            
        return exp


In [25]:

agent = MDPAgent()
agent.solve(is_bad_side=[1, 1, 1, 0, 0, 0])

max current =  5
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[0.   0.   0.   0.   0.17 0.17 0.17 0.   0.   0.   0.   0.   0.   0.5 ]
 [0.   0.   0.   0.   0.   0.17 0.17 0.17 0.   0.   0.   0.   0.   0.5 ]
 [0.   0.   0.   0.   0.   0.   0.17 0.17 0.17 0.   0.   0.   0.   0.5 ]
 [0.   0.   0.   0.   0.   0.   0.   0.17 0.17 0.17 0.   0.   0.   0.5 ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.17 0.17 0.17 0. 

1

## Test cases

We have provided some test cases for you to help verify your implementation.

In [4]:
## DO NOT MODIFY THIS CODE.  This code will ensure that your submission
## will work proberly with the autograder

import unittest

class TestDieNNotebook(unittest.TestCase):
    def test_case_1(self):
        agent = MDPAgent()
        np.testing.assert_almost_equal(
            agent.solve(is_bad_side=[1, 1, 1, 0, 0, 0]),
            2.583,
            decimal=3
        )
        
    def test_case_2(self):
        agent = MDPAgent()
        np.testing.assert_almost_equal(
            agent.solve(
                is_bad_side=[1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0]
            ),
            7.379,
            decimal=3
        )
        
    def test_case_3(self):
        agent = MDPAgent()

        np.testing.assert_almost_equal(
            agent.solve(
                is_bad_side=[1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0]
            ),
            6.314,
            decimal=3
        )

unittest.main(argv=[''], verbosity=2, exit=False)

test_case_1 (__main__.TestDieNNotebook) ... FAIL
test_case_2 (__main__.TestDieNNotebook) ... FAIL
test_case_3 (__main__.TestDieNNotebook) ... FAIL

FAIL: test_case_1 (__main__.TestDieNNotebook)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\hehez\AppData\Local\Temp\ipykernel_27908\2997006466.py", line 9, in test_case_1
    np.testing.assert_almost_equal(
  File "C:\Users\hehez\OneDrive\Github\tt1\venv\lib\site-packages\numpy\testing\_private\utils.py", line 599, in assert_almost_equal
    raise AssertionError(_build_err_msg())
AssertionError: 
Arrays are not almost equal to 3 decimals
 ACTUAL: 1
 DESIRED: 2.583

FAIL: test_case_2 (__main__.TestDieNNotebook)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\hehez\AppData\Local\Temp\ipykernel_27908\2997006466.py", line 17, in test_case_2
    np.testing.assert_almost_equal(
  File "C:\Users\h

max current =  5
[[[1.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.        ]
  [0.         1.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.        ]
  [0.         0.         1.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.        ]
  [0.         0.         0.         1.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.        ]
  [0.         0.         0.         0.         1.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.        ]
  [0.         0.         0.         0.         0.         1.
   0.         0.         0.         0.         0.         0.
   0.         0.        ]
  [0.         0.         0.         0.         0.         0.
   1.         0.         0.       